# Generated by Django 4.2.4 on 2023-08-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dog_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='фото'),
        ),
    ]
