# Generated by Django 4.2.4 on 2023-08-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_alter_dog_dog_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='дата рождения'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='dog_name',
            field=models.CharField(max_length=250, verbose_name='имя'),
        ),
    ]
