# Generated by Django 4.2.4 on 2023-08-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_alter_breed_description_alter_dog_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dog_photo',
            field=models.ImageField(blank=True, null=True, upload_to='dogs/', verbose_name='фото'),
        ),
    ]
