# Generated by Django 4.2.4 on 2023-09-05 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_alter_dog_dog_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=250, verbose_name='имя')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('breed_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogs.breed')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.dog')),
            ],
            options={
                'verbose_name': 'предок',
                'verbose_name_plural': 'предки',
            },
        ),
    ]
